---
- hosts: domain

  vars:
    ssh_tmpdir: "{{lookup('env','HOME')}}/autobuild_ssh"
    ssh_key_basename: "{{inventory_hostname | regex_replace('\\d?-mgmt$', '')}}"
    zfs_home_fs: rpool/apps/users
    domain: natinst.com
    pub_hostname: "{{inventory_hostname | regex_replace('-mgmt$', '')}}"

  tasks:
    # repos
  - name: Gather repo facts
    site_facts:
      types: [ "repos" ]
    tags:
      - repos
  - name: Remove IP-based Solaris repo
    pkg5_publisher:
      name: solaris
      state: absent
    when: current_solaris_repo != solaris_repo
    tags:
      - repos
  - name: Add name-based Solaris repo
    pkg5_publisher:
      name: solaris
      origin: "{{solaris_repo}}"
      sticky: true
    when: current_solaris_repo != solaris_repo
    tags:
      - repos
  - name: Add site repo
    pkg5_publisher:
      name: site
      origin: "{{site_repo}}"
      sticky: true
    when: current_site_repo != site_repo
    tags:
      - repos

    # pkgs
  - name: Install extra packages
    pkg5:
      name:
        - salt
        - ucb
        - vim
    tags:
      - pkgs
  - name: Install horcm on node 1
    pkg5: name=horcm
    when: inventory_hostname | match(".*1-mgmt$")
    tags:
      - pkgs
      - horcm

    # net
  - name: Setup RAC networks
    rac_net:
    tags:
      - net
  - name: Change hostname identity property
    command: "/usr/sbin/svccfg -s identity:node setprop config/nodename = astring: {{pub_hostname}}"
    tags:
      - net
  - name: Refresh identity service
    command: "/usr/sbin/svcadm refresh identity:node"
    tags:
      - net
  - name: Add public IP to hosts file
    lineinfile:
      dest: /etc/inet/hosts
      line: "{{lookup('dig', pub_hostname)}} {{pub_hostname}} {{pub_hostname}}.{{domain}}"
    tags:
      - net
  - name: Lookup private IPs
    set_fact:
      priv_lookup: "{{lookup('dig', item | regex_replace('-mgmt$', '-priv1'))}} {{item | regex_replace('-mgmt$', '-priv1')}}"
    with_items: "{{groups['domain']}}"
    register: privip_result
    tags:
      - net
  - name: Add private IPs to hosts file
    lineinfile:
      dest: /etc/inet/hosts
      line: "{{item}}"
    with_items: "{{ privip_result.results | map(attribute='ansible_facts.priv_lookup') | list }}"
    tags:
      - net

    # users
  - name: Create oracle user
    lineinfile:
      dest: /etc/passwd
      line: "oracle:x:{{oracle_uid}}:{{oinstall_gid}}:{{pub_hostname}}-oracle:/home/oracle:/usr/bin/bash"
    tags:
      - users
  - name: Create grid user
    lineinfile:
      dest: /etc/passwd
      line: "grid:x:{{grid_uid}}:{{oinstall_gid}}:{{pub_hostname}}-grid:/home/grid:/usr/bin/bash"
    tags:
      - users
      - disk
  - name: Create oracle ZFS homedir
    zfs:
      state: present
      name: "{{zfs_home_fs}}/oracle"
    tags:
      - users
  - name: Create grid ZFS homedir
    zfs:
      state: present
      name: "{{zfs_home_fs}}/grid"
    tags:
      - users
  - name: Set ownership on oracle homedir
    file:
      path: "/home/oracle"
      owner: oracle
      group: oinstall
    tags:
      - users
  - name: Set ownership on grid homedir
    file:
      path: "/home/grid"
      owner: grid
      group: oinstall
    tags:
      - users

    # ssh
  - name: Create local SSH tmpdir
    local_action: file state=directory path="{{ssh_tmpdir}}" mode=0700
    become: False
    tags:
      - ssh
  - name: Create local oracle SSH keypair
    local_action: "command /usr/bin/ssh-keygen -t dsa -C 'oracle@{{ssh_key_basename}}' -N '' -f {{ssh_tmpdir}}/{{ssh_key_basename}}-oracle creates={{ssh_tmpdir}}/{{ssh_key_basename}}-oracle"
    when: inventory_hostname | match(".*1-mgmt$")
    become: False
    tags:
      - ssh
  - name: Create local grid SSH keypair
    local_action: "command /usr/bin/ssh-keygen -t dsa -C 'grid@{{ssh_key_basename}}' -N '' -f {{ssh_tmpdir}}/{{ssh_key_basename}}-grid creates={{ssh_tmpdir}}/{{ssh_key_basename}}-grid"
    when: inventory_hostname | match(".*1-mgmt$")
    become: False
    tags:
      - ssh
  - name: Create oracle SSH dir
    file:
      state: directory
      path: "/home/oracle/.ssh"
      owner: oracle
      group: oinstall
      mode: 0700
    tags:
      - ssh
  - name: Create grid SSH dir
    file:
      state: directory
      path: "/home/grid/.ssh"
      owner: grid
      group: oinstall
      mode: 0700
    tags:
      - ssh
  - name: Copy oracle private key into place
    copy:
      src: "{{ssh_tmpdir}}/{{ssh_key_basename}}-oracle"
      dest: "/home/oracle/.ssh/id_dsa"
      mode: 0600
      owner: oracle
      group: oinstall
    tags:
      - ssh
  - name: Copy oracle public key into place
    copy:
      src: "{{ssh_tmpdir}}/{{ssh_key_basename}}-oracle.pub"
      dest: "/home/oracle/.ssh/id_dsa.pub"
      mode: 0644
      owner: oracle
      group: oinstall
    tags:
      - ssh
  - name: Copy oracle public key into auth keys
    copy:
      src: "{{ssh_tmpdir}}/{{ssh_key_basename}}-oracle.pub"
      dest: "/home/oracle/.ssh/authorized_keys"
      mode: 0644
      owner: oracle
      group: oinstall
    tags:
      - ssh
  - name: Copy grid private key into place
    copy:
      src: "{{ssh_tmpdir}}/{{ssh_key_basename}}-grid"
      dest: "/home/grid/.ssh/id_dsa"
      mode: 0600
      owner: grid
      group: oinstall
    tags:
      - ssh
  - name: Copy grid public key into place
    copy:
      src: "{{ssh_tmpdir}}/{{ssh_key_basename}}-grid.pub"
      dest: "/home/grid/.ssh/id_dsa.pub"
      mode: 0644
      owner: grid
      group: oinstall
    tags:
      - ssh
  - name: Copy grid public key into auth keys
    copy:
      src: "{{ssh_tmpdir}}/{{ssh_key_basename}}-grid.pub"
      dest: "/home/grid/.ssh/authorized_keys"
      mode: 0644
      owner: grid
      group: oinstall
    tags:
      - ssh

    # disk
  - name: Setup GRID disks
    grid_disk:
    tags:
      - disk
  
    # vfstab
#  - name: Add /opt/local to /etc/vfstab and mount it
#    mount:
#      src: aphrodite:/it/opt_local/opt/local
#      name: /opt/local
#      fstype: nfs
#      opts: vers=3,rsize=32768,wsize=32768,ro,intr,bg
#      state: mounted
#    tags:
#      - vfstab

    # horcm
  - name: Add horcm {{horcminst}} service instance
    horcm_setup:
      horcminst: "horcm{{horcminst}}"
      disk_groups: "{{rac_storage}}"
    when: inventory_hostname | match(".*1-mgmt$")
    tags:
      - horcm

    # salt
  - name: Add Salt master to /etc/hosts
    lineinfile:
      dest: /etc/hosts
      line: "{{salt_master_ip}}	salt"
    tags:
      - salt
  - name: Enable Salt minion
    service:
      name: salt-minion
      enabled: yes
    tags:
      - salt

# vim: tabstop=2 shiftwidth=2
