---
- hosts: domain

  tasks:
- name: Remove IP-based Solaris repo
  pkg5_publisher:
    name: solaris
    state: absent

- name: Add name-based Solaris repo
  pkg5_publisher:
    name: solaris
    origin: http://aisalt.natinst.com
    sticky: true

- name: Add site repo
  pkg5_publisher:
    name: site
    origin: http://aisalt.natinst.com:81
    sticky: true

- name: Install packages
  pkg5:
    name:
      - salt
      - ucb
      - vim

- name: Add Salt master to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{salt_master_ip}}	salt"

- name: Enable Salt minion
  service:
    name: salt-minion
    enabled: yes

- name: Import manifests
  service:
    name: manifest-import
    state: restarted

- name: Create oracle user
  user:
    name: oracle
    uid: 10
    group: oinstall
    generate_ssh_key: yes

- name: Create grid user
  user:
    name: grid
    uid: 61001
    group: oinstall
    generate_ssh_key: yes

- name: Install horcm on node 1
  pkg5:
    name:
      - horcm
  when: "{{inventory_hostname}}" == ~.*(1$)

- name: Copy scripts
  unarchive:
    src: scripts.tar
    dest: /tmp

- name: Setup ASM disks
  command: /tmp/scripts/ovm_rac_dsk_cfg_12c.sh

- name: Setup network
  command: /tmp/scripts/ovm_rac_net_cfg.sh "{{inventory_hostname}}"

- name: Setup horcm
  command: /tmp/scripts/horcm_setup.sh "{{horcm}}"

# vim: tabstop=2 shiftwidth=2
