---
- hosts: raidcom
  tasks:
  - name: Setup DATA storage for RAC environment "{{env_name}}"
    ldevblock:
      name: "{{env_name}}_DATA"
      horcm: "{{horcm}}"
      pool: "{{env_pool}}"
      hosts: "{{env_chassis}}"
      begin: "{{env_data_begin}}"
      end: "{{env_data_end}}"
      size: "{{env_data_size}}"
  - name: Setup FRA storage for RAC environment "{{env_name}}"
    ldevblock:
      name: "{{env_name}}_FRA"
      horcm: "{{horcm}}"
      pool: "{{env_pool}}"
      hosts: "{{env_chassis}}"
      begin: "{{env_fra_begin}}"
      end: "{{env_fra_end}}"
      size: "{{env_fra_size}}"
  - name: Setup OCR storage for RAC environment "{{env_name}}"
    ldevblock:
      name: "{{env_name}}_OCR"
      horcm: "{{horcm}}"
      pool: "{{env_pool}}"
      hosts: "{{env_chassis}}"
      begin: "{{env_ocr_begin}}"
      end: "{{env_ocr_end}}"
      size: "{{env_ocr_size}}"

# vim: tabstop=2 shiftwidth=2
