---
- hosts: storage

  tasks:
  - name: Setup {{ldom_name}} OS storage
    ldevblock:
      horcm: "{{horcm}}"
      pool: "{{os_pool}}"
      chassis: "{{os_chassis}}"
      ports: "{{os_ports}}"
      blocks: "{{os_blocks}}"
  - name: Setup RAC env storage
    ldevblock:
      horcm: "{{horcm}}"
      pool: "{{env_pool}}"
      chassis: "{{env_chassis}}"
      ports: "{{env_ports}}"
      blocks: "{{env_blocks}}"

# vim: tabstop=2 shiftwidth=2
