---
- hosts: storage

  tasks:
  - name: Setup OS storage
    ldevblock:
      horcm: "{{horcminst}}"
      blocks: "{{os_blocks}}"
    tags:
      - os
  - name: Setup RAC env storage
    ldevblock:
      horcm: "{{horcminst}}"
      blocks: "{{env_blocks}}"
    tags:
      - env

# vim: tabstop=2 shiftwidth=2
