---
- name: Create oracle user
  user:
    name: oracle
    uid: 10
    group: oinstall
    generate_ssh_key: yes

- name: Create grid user
  user:
    name: grid
    uid: 61001
    group: oinstall
    generate_ssh_key: yes

- name: Install horcm
  pkg5:
    name:
      - horcm

- name: Copy scripts
  unarchive:
    src: scripts.tar
    dest: /tmp

- name: Setup ASM disks
  command: /tmp/scripts/ovm_rac_dsk_cfg_12c.sh

- name: Setup network
  command: /tmp/scripts/ovm_rac_net_cfg.sh "{{inventory_hostname}}"

- name: Setup horcm
  command: /tmp/scripts/horcm_setup.sh "{{horcminst}}"
